language: python
python:
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: jvfe
  on:
    tags: true
    repo: jvfe/pytrials
    python: 3.8
  password:
    secure: OM3YedevUUej5zDEimlyxc06BELeKIzqXJHDNM/AJ/9JHqjLWmn6ga0QRg4qw4APyCdsFKvjpoXbDJMVCUoWji9gW3FG2SV6pQNjgiEcpgo19e+GsWAxtvMXGkJ0NwH2pAIJNjAXHCbVlXu2fP/ReCW/Yk+CRYGb57epqUn+A8CKvdSKtxiMeo5V2WbNb88s3jtiWZJcmMSSFs1clqiSfMyMS+ynFd1yaR6QL1Yr6l+l/UbBZfzPN17Plsedw0sD6DyQR6+M/XVMyaweCVoY+f1CoNyHxp16EGtPmaifV9TmFY9EOEi/y2J+anrMNPOO/oizlfTSMp/WBzSpyeuqvrNyNKAcfVVhhq9+S34oD3o7fE/9Zh3empYk9gIxTtbiprXWjS3F0V9AenjMonhTcext/bnVhLPfUSPOZCed4HYEefJxg+4bw1mljbUhzxJdZcakg1K96iKdGQ6FynbkdDPUeTzBHjYg3gKOMg4xdR1wfR3hz/R01dwgEL0QeELREbpHwxenNV4B4dMwt1ZuHlqz+/Jma6GkrlCDAwYszbMQNlJRF83RI/ez3qNNhbT7QgKXhz/1WDq+eW+gNiTYC2HwXGcAq24rl2QTQ+pYwrcdmX9BcE7ehRCOsnl3vEp0FnMW+8bBiq16nTYatlhP09ut/zHDh/zhLSrPsf0RVNs=
